# Generated by Django 5.1.7 on 2025-03-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_of_item/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=200000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Product_Image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Product_Image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Product_Image/')),
                ('Category_of_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='items.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('note_to_lender', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('storage', 'At Storage'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], default='storage', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('tracking_key', models.CharField(editable=False, max_length=20, unique=True)),
                ('Category_of_items_checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category_item_checkout', to='items.itemcategory')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='items.product')),
            ],
        ),
    ]
