# Generated by Django 5.1.7 on 2025-03-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='last_name',
        ),
    ]
