# Generated by Django 5.1.7 on 2025-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='status',
            field=models.CharField(choices=[('storage', 'At Storage'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='storage', max_length=20),
        ),
    ]
