# Generated by Django 5.2 on 2025-05-29 09:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_checkoutinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='image',
            field=cloudinary.models.CloudinaryField(default=3, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image3'),
            preserve_default=False,
        ),
    ]
