# Generated by Django 5.2 on 2025-06-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'General Setting', 'verbose_name_plural': 'General Setting'},
        ),
    ]
